### ISSUE TITLE
请教skynet是如何成功加载logger.so的?

### ISSUE THREAD

**Issue by Tancen** [cloudwu/skynet#807]
在终端内输入 ldd -r logger.so ，输出

linux-vdso.so.1 =>  (0x00007ffdcbb02000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6a3dfe8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6a3e5ca000)
undefined symbol: skynet_command	(./logger.so)
undefined symbol: skynet_callback	(./logger.so)

其中，skynet_command 和 skynet_callback 是未定义的。
我特地开了个测试工程，和 skynet 一样用 dlopen 带上 RTLD_NOW | RTLD_GLOBAL 来打开 logger.so，返回的是0，错误信息是 ./logger.so: undefined symbol: skynet_command。其它3个动态库也是类似这种情况。
本人技术水平有限，实在没弄懂 skynet 是如何成功加载的（我在 skynet dlopen 后面加了一行打印代码，测试出skynet确实成功加载了 logger.so），希望可以的话，能告知一下，谢谢了

**Comment by cloudwu** [comment]
`skynet_command` `skynet_callback` 这些符号是在主程序中提供的。首先你的主程序要实现这些符号。

**Comment by Tancen** [comment]
起初发现这个问题是我把 skeynet 的所有文件加到一个 qt 工程内，然后编译完工程跑起来的时候，提示 logger.so 加载失败，所以就单独建立了个测试工程。刚才按照您的提示，在测试工程内实现了空的 skynet_command 和 skynet_callback，并且从 skynet 内拷贝了相关类型的定义，编译后执行依然会提示 ./logger.so: undefined symbol: skynet_command

**Comment by firedtoad** [comment]
你不能gdb下个条件断点自己跟么，问这种问题有意思么

2018年3月7日 12:51，"Tancen" <notifications@github.com>写道：

起初发现这个问题是我把 skeynet 的所有文件加到一个 qt 工程内，然后编译完工程跑起来的时候，提示 logger.so
加载失败，所以就单独建立了个测试工程。刚才按照您的提示，在测试工程内实现了空的 skynet_command 和
skynet_callback，并且从 skynet 内拷贝了相关类型的定义，编译后执行依然会提示 ./logger.so: undefined
symbol: skynet_command

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cloudwu/skynet/issues/807#issuecomment-371022029>, or mute
the thread

**Comment by Tancen** [comment]
dlopen直接返回0了，设断点有什么意义？

**Comment by firedtoad** [comment]
安装系统调试符号，调试断点打在dlopen上 带上断点参数不可以么

2018年3月8日 13:48，"Tancen" <notifications@github.com>写道：

**Comment by cloudwu** [comment]
objdump -t 看看符号导出。这种和项目无关的问题在这里提好像不太合适。

**Comment by Tancen** [comment]
objdump -t 是能看到 skynet_command，但是依然会打开失败的。花了几个小时查找资料，发现需要在链接的时候加上 -rdynamic 参数才能正确加载
多谢了
